/*
 * openinput.h : Top-level include file for OpenInput
 *
 * This file is a part of the OpenInput library.
 * Copyright (C) 2005  Jakob Kjaer <makob@makob.dk>.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

/* ******************************************************************** */

#ifndef _OPENINPUT_H_
#define _OPENINPUT_H_

#ifdef __cplusplus
extern "C" {
#endif

/* ******************************************************************** */

/**
 * @ingroup PMain
 * @{
 */

// Fix Windows
#if !defined(WIN32) && defined(_WIN32)
#define WIN32
#endif

// Export keyword
#ifndef DECLSPEC
#  ifdef WIN32
#    define DECLSPEC __declspec(dllexport) /**< Export keyword, Windows */
#  else
#    define DECLSPEC  /**< Export keyword, default */
#  endif
#endif

// Calling convention
#ifndef OICALL
#  if defined(WIN32) && !defined(__GNUC__)
#    define OICALL __cdecl  /**< Calling convention, Windows */
#  else
#    define OICALL  /**< Calling convention, default */
#  endif
#endif

/** @} */

/* ******************************************************************** */

/**
 * @ingroup PMain
 * @{
 */
#define OI_MAJOR_VERSION 0 /**< Major version number (autogenerated) */
#define OI_MINOR_VERSION 2 /**< Minor version number (autogenerated) */
#define OI_PATCH_VERSION 3 /**< Patch version number (autogenerated) */
#define OI_VERSION "0.2.3" /**< Version as a string (autogenerated) */
/** @} */

/* ******************************************************************** */

#include "openinput_types.h"
#include "openinput_keyboard.h"
#include "openinput_mouse.h"
#include "openinput_joystick.h"
#include "openinput_action.h"
#include "openinput_events.h"
#include "openinput_api.h"

/* ******************************************************************** */

#ifdef __cplusplus
}
#endif

#endif
